### ISSUE TITLE
The eidas-bridge docker does not start 

### ISSUE THREAD

**Issue by tomasbbb** [validatedid/eidas-bridge#10]
Traceback (most recent call last):
  File "/code/demo/eidas_start_demo.py", line 10, in <module>
    from demo.eidas_bridge_api import init_api_server
  File "/code/demo/eidas_bridge_api.py", line 7, in <module>
    from flask_restplus import Resource, Api, fields, abort
  File "/usr/local/lib/python3.7/dist-packages/flask_restplus/__init__.py", line 4, in <module>
    from . import fields, reqparse, apidoc, inputs, cors
  File "/usr/local/lib/python3.7/dist-packages/flask_restplus/fields.py", line 17, in <module>
    from werkzeug import cached_property
**ImportError: cannot import name 'cached_property' from 'werkzeug' (/usr/local/lib/python3.7/dist-packages/werkzeug/__init__.py)**

Tested under under linux ubuntu 16.04

**Comment by 6d7a** [comment]
I was able to circumvent the error by using [flask-restx](https://github.com/python-restx/flask-restx) instead of flask-restplus.
File "/code/demo/eidas_bridge_api.py", line 7 `from flask_restx import Resource, Api, fields, abort`
File "/code/requirements.demo.txt", add `flask-restx`
